### ISSUE TITLE
How much VRAM does it need?

### ISSUE THREAD

**Issue by nitinmukesh** [nftblackmagic/catvton-flux#1]
Looking at the model size, it seems quantized version will not work with consumer GPU.

**Comment by nftblackmagic** [comment]
Yep. This is the first version I run with full parameter finetuning. Plan to release small VRAM usage model in the future.

**Comment by nitinmukesh** [comment]
Thanks for letting us know. We will wait for the smaller version.

**Comment by nftblackmagic** [comment]
Add VRAM in README with https://github.com/nftblackmagic/catvton-flux/commit/44301b0461e9a3b18933d591977d3e09dfcbc665
