### ISSUE TITLE
【Not An Issue】A wrapper for catvton-flux: ComfyUI-CatvtonFluxWrapper

### ISSUE THREAD

**Issue by lujiazho** [nftblackmagic/catvton-flux#14]
Currently you can install by git clone under custom-nodes: https://github.com/lujiazho/ComfyUI-CatvtonFluxWrapper. Already made a pull request to ComfyUI-Manager, and you may be able to install it from ComfyUI-Manager in the future.

<img width="960" alt="391195876-5d3cb124-1988-433e-b2fa-0a6102a7ed89" src="https://github.com/user-attachments/assets/1d9f12b8-9f56-4308-85ea-c53aac1acc84">

By the way, thanks to @nftblackmagic for such great work!

**Comment by nftblackmagic** [comment]
Thank you for the supporting! Updated README for the wrapper. https://github.com/nftblackmagic/catvton-flux/commit/a18f098e86403b48c184282007ecfe821f1f273f
