### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by AgentScrubbles** [nftblackmagic/catvton-flux#20]
First off, great work.  Truly great.

Now, know that there are many companies out there who are trying to do this same thing on their websites.  I implore that you IMMEDIATELY add an official license file to this project before they come and fork it and use it without ever giving you credit or thought.  (I see you have MIT, if you want to stick with that then great, but know that any company like Amazon or Macy's can use your code here for free, and even then I would suggest adding the official LICENSE file.)

Personally, I recommend GPL, or some variant that allows other open source projects to use your code, but closed source proprietary projects need to license it from you.  

This could be a very valuable project to some large companies.

https://choosealicense.com/

(If you don't want to or can't or anything feel free to close this, no harm at all, but I don't want you to not know and then have Macy's or Nordstrom use your code for free)

**Comment by nftblackmagic** [comment]
Thanks for reminding. Added License files. 

For the code inside this project, I will keep it as MIT. The code here is really simple and from diffusers official examples. I can keep the code simple and make sure anyone who wants to use it can use it. 

For the model, it's from flux-dev-fill and VTON-HD. The license is combined with FLUX and VTON-HD licenses. The model is only for researches.
