### ISSUE TITLE
Citation for VTOFF task

### ISSUE THREAD

**Issue by rizavelioglu** [nftblackmagic/catvton-flux#22]
Hey there, this is Riza, the author of [TryOffDiff](https://rizavelioglu.github.io/tryoffdiff). 
First of all, great work on your repo—it’s fantastic to see such a swift adoption of the Virtual Try-Off (VTOFF) task!

I’d kindly like to request that you add citation information for our paper in your repository. Proper attribution would mean a lot to us as it helps the community recognize and build upon the original work :)

```bash
@article{velioglu2024tryoffdiff,
  title     = {TryOffDiff: Virtual-Try-Off via High-Fidelity Garment Reconstruction using Diffusion Models},
  author    = {Velioglu, Riza and Bevandic, Petra and Chan, Robin and Hammer, Barbara},
  journal   = {arXiv preprint arXiv:2411.18350},
  year      = {2024},
  note      = {\url{https://doi.org/nt3n}}
}
```
Thank you so much for your understanding, and keep up the great work!

**Comment by nftblackmagic** [comment]
Hi Riza,

Thank you for bringing your work to our attention. Our implementation was developed independently, inspired by feedback from a community member's comment on my social media post as follows. While it's interesting that we arrived at similar ideas, our work was not derived from or influenced by your implementation. Such parallel development of similar ideas often occurs naturally in the open source community.

<img width="558" alt="Screenshot 2024-12-14 at 11 29 15 AM" src="https://github.com/user-attachments/assets/a0ffc172-71ab-4c34-914d-25fbfa3b0d52" />
http://xhslink.com/a/9LCAbiMTlJF1

Thanks,
An
