### ISSUE TITLE
衣服类型

### ISSUE THREAD

**Issue by cyy-1234** [nftblackmagic/catvton-flux#4]
作者你好，现在这个模型支持哪些品类呀，使用gradio大概要多大显存够用，输出的尺寸是否可以更大

**Comment by nftblackmagic** [comment]
基于公开的数据，现在这个模型只支持女装上衣，可能最核心的问题是没有更多的公开数据集。

**Comment by nftblackmagic** [comment]
输出的尺寸和flux模型一样 1024上应该表现是最好，如果未来flux模型更大，支持尺寸应该会更多。但是我的模型训练只是在768的维度上完成的。更高的维度需要的算力更多，没有那么高的预算。
